version: '3.3'

services:
  postgres:
    image: postgres:13
    environment: 
      - POSTGRES_DB=my_store
      - POSTGRES_USER=anubis
      - POSTGRES_PASSWORD=anubis264
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: anubis264
      MYSQL_DATABASE: my_store
      MYSQL_USER: anubis
      MYSQL_PASSWORD: anubis264
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql